// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Api.EntityFramework;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalApiPeliculas.Entity.Persona", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Persona", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Apellidos = "Perez",
                            DocumentoIdentidad = "12345678",
                            Estado = "A",
                            FechaNacimiento = new DateTime(2024, 3, 25, 17, 0, 37, 438, DateTimeKind.Local).AddTicks(3574),
                            Nombres = "Juan"
                        },
                        new
                        {
                            Id = "2",
                            Apellidos = "Lopez",
                            DocumentoIdentidad = "87654321",
                            Estado = "A",
                            FechaNacimiento = new DateTime(2024, 3, 25, 17, 0, 37, 438, DateTimeKind.Local).AddTicks(3590),
                            Nombres = "Maria"
                        },
                        new
                        {
                            Id = "3",
                            Apellidos = "Gomez",
                            DocumentoIdentidad = "45678912",
                            Estado = "A",
                            FechaNacimiento = new DateTime(2024, 3, 25, 17, 0, 37, 438, DateTimeKind.Local).AddTicks(3592),
                            Nombres = "Carlos"
                        },
                        new
                        {
                            Id = "4",
                            Apellidos = "Garcia",
                            DocumentoIdentidad = "78912345",
                            Estado = "A",
                            FechaNacimiento = new DateTime(2024, 3, 25, 17, 0, 37, 438, DateTimeKind.Local).AddTicks(3593),
                            Nombres = "Luis"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
